### ISSUE TITLE
Package Debugging

### ISSUE THREAD

**Issue by ManuelHentschel** [ManuelHentschel/VSCode-R-Debugger#104]
*(Follow-up on https://github.com/ManuelHentschel/VSCode-R-Debugger/issues/56, @pat-s)*

In [VSCode-R-Debugger/packageDebugging](https://github.com/ManuelHentschel/VSCode-R-Debugger/tree/packageDebugging) and [vscDebugger/packageDebugging](https://github.com/ManuelHentschel/vscDebugger/tree/packageDebugging), I've started working on making the workflow for debugging packages more "dynamic".

I've added the debug config entry `loadPackages`, which indicates paths (!) to packages that are loaded with `pkgload::load_all` before launching the debugger. To load the package from the working directory, this entry can be set to `["."]`. To set breakpoints in these packages it is currently necessary to set `"setBreakpointsInPackages": true`. An example launch config that can be used to debug the package from the current wd could be:
``` jsonc
        {
            "type": "R-Debugger",
            "request": "launch",
            "name": "Launch Workspace",
            "debugMode": "workspace",
            "workingDirectory": "${workspaceFolder}",
            "loadPackages": ["."],
            "setBreakpointsInPackages": true,
            "includePackageScopes": true,
            "allowGlobalDebugging": true
        }
```

Some considerations/questions I have about how to continue from here:
* Manually calling `load_all` resets all breakpoints set in the loaded package. This could be solved by replacing the function with a wrapper around the original function, that also sets the breakpoints. In that case it might not even be necessary to specify "loadPackages", since the breakpoints will be set anyways.
* Currently, "setBreakpointsInPackages" is disabled by default and limited to exported functions, because I experienced some performance hits when looking for multiple breakpoints in the exported+private functions from every package. An option here might be to skip R's standard packages (base, utils, methods, ...), but still look in all custom packages.
* Only allowing the user to specify the package path might be a bit inflexible, if users want to pass custom arguments to `load_all`, or maybe even use an entirely different function to load their package. In that case it might make sense to allow the user to specify "pre-launch-commands" instead, that are executed before setting breakpoints and overwriting print/cat/message.

Any thoughts on the points above or debugging-scenarios I am missing? :)

**Comment by pat-s** [comment]
Thanks, sounds great!

> To load the package from the working directory, this entry can be set to ["."]

Will this also work recursively? Some people work in a monorepo approach, hence the packages are stored in subdirectories of the project root.

I am wondering: is this setting ever altered by the user? If not, could it be set internally?
The same idea applies to other settings in `launch.json`: If these are fixed/required for a specific debug mode, these could be set internally and not exposed to the user at all.

This would follow the philosophy of having certain "fixed" debug modes (e.g. for packages) and maybe one flexible one which users could alter in any case. This would strip down `launch.json` a bit. (just an idea though, you might know better or have a different philosophy here :) )

> This could be solved by replacing the function with a wrapper around the original function, that also sets the breakpoints. 

Sounds promising! It would be great if breakpoint are not invalidated when calling `load_all()`.

>  if users want to pass custom arguments to load_all, or maybe even use an entirely different function to load their package.

in 99% of all cases, `load_all()` is called with its defaults. I haven't ever altered any argument of the function. This is also the general idea of it AFAIU - quickly reloading the current dev state with a shortcut.  Hence I would not weight flexibility of passing args to it too high.

General flexibility is of course always great but maybe a point for future releases - given that `load_all()` is the canonical way in a dev workflow in 99% of all cases.

**Comment by ManuelHentschel** [comment]
> Will this also work recursively? Some people work in a monorepo approach, hence the packages are stored in subdirectories of the project root.

In that scenario, what would your "normal" workflow look like? Do you launch the R process in the project root or one of the subdirectories (i.e. what directory does `getwd()` return)? Do you somehow load all packages (is there something like `load_all('**/*')`?) or just the one you are working on?

**Comment by pat-s** [comment]
> Do you launch the R process in the project root or one of the subdirectories (i.e. what directory does getwd() return)?

My WF has the R package in the project root (which might apply to 80-90% of other devs). Just a pointer if you aim to make the implementation more generic to account for the other "monorepo" case.

Hence I cannot comment on how pkg dev is done in a monorepo scenario, given that `pkgload::load_all()` would not work OOB as it always uses the current directory AFAIK.

If a user starts the process while focusing an R file, maybe searching for the corresponding `DESCRIPTION` file in the parent directories and using this one as the current project root could work?

**Comment by ManuelHentschel** [comment]
> Sounds promising! It would be great if breakpoint are not invalidated when calling `load_all()`.

I just pushed a commit that adds a modified `load_all`.

In addition to refreshing breakpoints after calling `pkgload::load_all`, this function also remembers the namespace and exports of the loaded package for new breakpoints that are set/changed afterwards.

This approach could even solve some of the discussion above, since you can simply call `load_all` in your own scripts/the debug console without worrying about specifying the packages in the launch config.

**Comment by ManuelHentschel** [comment]
> Hence I cannot comment on how pkg dev is done in a monorepo scenario, given that `pkgload::load_all()` would not work OOB as it always uses the current directory AFAIK.
> 
> If a user starts the process while focusing an R file, maybe searching for the corresponding `DESCRIPTION` file in the parent directories and using this one as the current project root could work?

With the modified `load_all`, we could leave it to the user to load the correct package(s) and the breakpoints would be set in these packages automatically.

**Comment by ManuelHentschel** [comment]
>  The same idea applies to other settings in `launch.json`: If these are fixed/required for a specific debug mode, these could be set internally and not exposed to the user at all.
> 
> This would follow the philosophy of having certain "fixed" debug modes (e.g. for packages) and maybe one flexible one which users could alter in any case. This would strip down `launch.json` a bit. (just an idea though, you might know better or have a different philosophy here :) )

Most of the entries in launch.json are not required (with the latest push, only the ones mandated by vscode itself `name`, `type`, `command` are required) and filled with defaults by the vscode extension before passing the configuration to R.

I just added the four default entries to give users an idea of what combinations of configurations might be sensible. If you prefer to have a smaller file, you can remove the configurations that you don't use and delete the lines where you are happy with the defaults.
