### ISSUE TITLE
Respect user settings of CRAN repos in use

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/VSCode-R-Debugger#108]
The `rdebugger.updateRPackage` command runs the following command in the terminal:

```
/usr/local/bin/R --vanilla --silent -e "install.packages('https://github.com/ManuelHentschel/VSCode-R-Debugger/releases/download/v0.4.2/vscDebugger_0.4.2.tgz', repos=NULL)" -e "install.packages('jsonlite', repos='http://cran.r-project.org')" -e "install.packages('R6', repos='http://cran.r-project.org')"
```

This does not respect user settings of CRAN mirror.

I guess we could run an R script in which if `repos` option is customized then we should respect that option.

This could be useful if user is working in a network with limitations.

**Comment by ManuelHentschel** [comment]
I'm not really familiar with the available options here, but I'll be happy to merge, if you find a safer/more efficient way to install the package(s) :)

**Comment by tdeenes** [comment]
`getOption("repos")$CRAN`

**Comment by renkun-ken** [comment]
The following should work:

```r
repos <- getOption("repos")
if (is.null(cran) || identical(repos, c(CRAN = "@CRAN@"))) {
  repos <- c(CRAN = "https://cloud.r-project.org/")
}

install.packages(c("jsonlite", "R6"), repos = repos)
install.packages('https://github.com/ManuelHentschel/VSCode-R-Debugger/releases/download/v0.4.2/vscDebugger_0.4.2.tgz', repos = NULL)
```

If the repos is not set, then the default value is "@CRAN@".
