### ISSUE TITLE
Upload the extension to Open VSX

### ISSUE THREAD

**Issue by saerosV** [ManuelHentschel/VSCode-R-Debugger#125]
Seeing that some open source builds of VS Code, in some GNU/Linux distributions (e.g., Archlinux and Manjaro) use the **Open VSX** repository instead of **VS Marketplace** to install extensions: 
https://wiki.archlinux.org/index.php/Visual_Studio_Code#No_extensions_found

I'd like to suggest uploading **R-Debugger** in the [Open VSX](https://open-vsx.org/) repo, to improve the extension's visibility and make it more convenient for future users to install it.

**Comment by ManuelHentschel** [comment]
Thanks for the suggestion, I uploaded the extension [here](https://open-vsx.org/extension/RDebugger/r-debugger) and opened an [issue](https://github.com/EclipseFdn/open-vsx.org/issues/385) to claim ownership of the namespace.

I'll try to update the GitHub Actions to publish to ovsx as well before the next release.

**Comment by saerosV** [comment]
Glad to help, looking forward to RDebuggers's next release.
