### ISSUE TITLE
Breakpoints in "Debug R-Package" are not loaded/hit

### ISSUE THREAD

**Issue by hechth** [ManuelHentschel/VSCode-R-Debugger#126]
**Describe the bug**
When debugging an R package by entering the path to the package folder structure, the breakpoints set within the files which are part of the package aren't entered, i.e the program doesn't always stop. The behaviour seems to be a bit random.

**To Reproduce**
1. Open a folder containing the R package to debug in the folder structure.
2. Open the "launch.json" file and enter the path to the package in the entry "loadPackages" in the "Debug R-Package" entry in the json.
3. Click "Run" button in the debugger with the "Debug R-Package" option selected.
4. Use the debug console to call a function exported in the package.
5. If the program stops at a breakpoint set before, set a new breakpoint and press "F5".
6. Not see your breakpoint get hit.

**Your Launch config**
If applicable, the launch config that causes the bug. E.g.:
``` json
    {
        "type": "R-Debugger",
        "name": "Debug R-Package",
        "request": "launch",
        "debugMode": "workspace",
        "workingDirectory": "${workspaceFolder}",
        "includePackageScopes": true,
        "loadPackages": [
            "./apLCMS"
        ]
    }
```

**Expected behavior**
Upon debugging the package, all breakpoints set are hit properly and stop program execution.

**Actual behavior**
Some breakpoints are hit, some aren't, some in other files than the one opened on startup are never hit.

**Desktop (please complete the following information):**
 - OS: Windows
 - R Version: 4.0.3
 - vscDebugger Version: 0.4.5
 - vscode-r-debugger Version: v0.4.5

**Comment by ManuelHentschel** [comment]
Setting and unsetting breakpoints while the program is stopped can be a bit hit or miss, since the body of the currently executed function cannot be modified (which is done to set breakpoints). Therefore, setting a breakpoint in the same function as the breakpoint where you're currently stopped usually won't work:
``` r
f <- function(){
    print(1) # <-- Set breakpoint here
    print(2)
    print(3) # <-- Setting breakpoint here while stopped on first breakpoint won't work
    print(4)
}
f()
```

If a function is called repeatedly, the new breakpoint should work on the next iteration though:
*(This example works with debug mode "Debug R-Function")*
``` r
f <- function(){
    print(1) # <-- Setting breakpoint here while stopped on the other breakpoint should work on the next iteration
    print(2)
    print(3) # <-- Set breakpoint here
    print(4)
}

main <- function(){
    for(i in 1:2){
        f()
    }
}
```



Setting breakpoints in a function that is not being executed should always work:
``` r
f <- function(){
    print(1) # <-- Set breakpoint here
    print(2)
    g()
    print(4)
}
g <- function(){
    print(3) # <-- Setting breakpoint here while stopped on the other breakpoint should work
}
f()
```

Does this behaviour match your observations?

**Comment by hechth** [comment]
Thank you very much for the comment - I by now figured out some rather consistent behaviour for debugging and yes, I think this matches my observations.

I will watch out for behaviour specific to functions and function invocation.

**Comment by ManuelHentschel** [comment]
I added a Vignette about breakpoints to the package (can be found e.g. [here](https://manuelhentschel.github.io/vscDebugger/articles/breakpoints.html)). If you encounter problems that do not match the behavior described there or would like to add your debugging routine, feel free to reopen this issue.

**Comment by hechth** [comment]
@kongdd I had the same error at some point and it was related to the version of the packagetools package (I think that was the name). So try seeing which version you are using
