### ISSUE TITLE
How to make the View() and plot() command work like vscode-R?

### ISSUE THREAD

**Issue by xiajunwen1007** [ManuelHentschel/VSCode-R-Debugger#146]
**Describe the bug**
When I debug a file and use the command View() or plot(), a new program window, like XQuartz, will pop up. Is there a way to open a new window inside vscode like VSCODE-R.

**To Reproduce**
```
my_function <- function(){
    df <- cars
    print('inside function') # <-- breakpoint here. Then run `View(df)` in debug console.
}

my_function()
```
Set a breakpoint at `print()`, then type `View(df)`.

**Screenshot**
![iShot2021-07-16 09 59 09](https://user-images.githubusercontent.com/49160447/125880170-d4abceea-b300-455b-a797-f6b7e6a1cfcf.gif)

**Comment by ManuelHentschel** [comment]
You can add the following code to your .Rprofile in order to have these overwrites:
``` r
if(Sys.getenv('VSCODE_DEBUG_SESSION')=='1'){
    Sys.setenv(TERM_PROGRAM='vscode')
    source(file.path(Sys.getenv(if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"), ".vscode-R", "init.R"))
}
```

Some functions (like the httpgd based plot viewer) might be a bit buggy though.

**Comment by xiajunwen1007** [comment]
It doesn't work. I'm a Mac user, so maybe the code `.Platform$OS.type == "windows"` should change to `.Platform$OS.type == "unix"`?

**Comment by ManuelHentschel** [comment]
Can you please try running the two lines inside the `if` part, e.g. as part of your .R file, and see if anything changes/any errors occur?
``` r
    Sys.setenv(TERM_PROGRAM='vscode')
    source(file.path(Sys.getenv(if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"), ".vscode-R", "init.R"))
```

**Comment by xiajunwen1007** [comment]
Thank you for your reply. Nothing happens. No errors and no changes. When I uninstall XQuartz, and try the command `View()`. There is no errors reminding me to install XQuartz. So I guess it works partly.

**Comment by ManuelHentschel** [comment]
The sequence used to attach the modified versions of `View()` etc. is somewhat tricky. To manually reproduce it, please create a workspace with an empty `.Rprofile`, add a file that contains
``` r
print(View)
Sys.setenv(TERM_PROGRAM= 'vscode')
source(file.path(Sys.getenv(if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"), ".vscode-R", "init.R"))
.First.sys()
print(View)
```
and run this file in the debugger (e.g. using the default debug config `Debug R-File`).

If everything works as expected, the two print commands should print two different functions: first the original `utils::View`, then the modified version from vscode-R.

**Comment by xiajunwen1007** [comment]
Thank you very much! The two print commands do print different functions. Now everything works fine by your reply on the second floor. I cannot figure out why it doesn't work before.

**Comment by ManuelHentschel** [comment]
In my second reply, I forgot to mention that you have to manually call `.First.sys()`. This function is called as part of the R startup sequence after sourcing .Rprofile, so it is not needed, if the code is in the .Rprofile. But it needs to be called, if you are sourcing init.R after the startup is done.



> You can add the following code to your .Rprofile in order to have these overwrites:
> 
> ```r
> if(Sys.getenv('VSCODE_DEBUG_SESSION')=='1'){
>     Sys.setenv(TERM_PROGRAM='vscode')
>     source(file.path(Sys.getenv(if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"), ".vscode-R", "init.R"))
> }
> ```
> 
> Some functions (like the httpgd based plot viewer) might be a bit buggy though.

Did you get this to work, as well?

**Comment by xiajunwen1007** [comment]
Yes, I get it to work. I have a unique workspace for writing R. When I restart the vscode, almost all keep. Maybe, in this case, I need only call `.First.sys()` once? 
Yep, it is buggy. The `bar()` command would introduce a bug for `plot`. And when I right click a variable and click _show in data viewer_, nothing happens and the debugger console cannot respond any command.
Though it is buggy, It is much better than xQuratz. At last, thank you very much.

**Comment by ManuelHentschel** [comment]
> Yes, I get it to work. I have a unique workspace for writing R. When I restart the vscode, almost all keep. Maybe, in this case, I need only call `.First.sys()` once?

Ideally, you can have code mentioned above in your .Rprofile, and `.First.sys` is called automatically by R itself during the startup sequence. In this case you don't have to call `.First.sys` at all.

**Comment by xiajunwen1007** [comment]
thank you！

**Comment by mdreier** [comment]
@ManuelHentschel Could you please add this information to the readme? It took me a while to find this issue and get the plots working with the debugger.

**Comment by ymansiaux** [comment]
> In my second reply, I forgot to mention that you have to manually call `.First.sys()`. This function is called as part of the R startup sequence after sourcing .Rprofile, so it is not needed, if the code is in the .Rprofile. But it needs to be called, if you are sourcing init.R after the startup is done.
> 
> > You can add the following code to your .Rprofile in order to have these overwrites:
> > if(Sys.getenv('VSCODE_DEBUG_SESSION')=='1'){
> >     Sys.setenv(TERM_PROGRAM='vscode')
> >     source(file.path(Sys.getenv(if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"), ".vscode-R", "init.R"))
> > }
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Some functions (like the httpgd based plot viewer) might be a bit buggy though.
> 
> Did you get this to work, as well?

Hi @ManuelHentschel thanks so much for your work with the r debugger.

The last thing that still was a pain for me was the displaying of data frames and plots who was not integrated in the same viewer than in "regular" mode.

Setting this in my RProfile solved the problem. Do you think it could be done by default, or maybe referencing it in the README ?

Thanks very much

BW

Yohann
