### ISSUE TITLE
Define a environemnt variable to indicate debug session

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/VSCode-R-Debugger#15]
[vscode-R session watcher](https://github.com/Ikuyadeu/vscode-R/pull/150) could be activated in `.Rprofile` for any interactive session if users follows the instructions at https://github.com/Ikuyadeu/vscode-R#advanced-usage-for-self-managed-r-sessions.

It makes sense to me that a debug session should not activate session watcher because it will attach automatically in replacement of the user session. If an environment variable is defined before launching the debug R session, then we have a chance in `.Rprofile` or session watcher init script to avoid activating the session watcher.

I take a look at https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options and it could be easily done by specifying `env` in `options`.

BTW, I'm wondering if there's a reason to use a user specified `terminalPath` instead of the built-in support of running command in `shell`?

**Comment by ManuelHentschel** [comment]
Looks good. There might even be some potential to combine the debugger and session watcher to watch existing R session using VS Code's debug interface (stack frames, scopes, variables window etc.) :)

**Comment by ManuelHentschel** [comment]
Regarding the `terminalPath`: I haven't tried the `shell` option yet so I will look into that. Thanks for the tip!

**Comment by ManuelHentschel** [comment]
Works like a charm, thanks again!

**Comment by renkun-ken** [comment]
Thanks!
