### ISSUE TITLE
Word completion during debugging

### ISSUE THREAD

**Issue by ManuelHentschel** [ManuelHentschel/VSCode-R-Debugger#17]
@renkun-ken I have seen that you did some work on the R language server https://github.com/REditorSupport/languageserver. The debug protocol also offers a possibility to have word completions from a debug session using `CompletionRequest`s:
``` ts
    interface CompletionsRequest extends Request {
        arguments: CompletionsArguments;
    }
    /** Arguments for 'completions' request. */
    interface CompletionsArguments {
        /** Returns completions in the scope of this stack frame. If not specified, the completions are returned for the global scope. */
        frameId?: number;
        /** One or more source lines. Typically this is the text a user has typed into the debug console before he asked for completion. */
        text: string;
        /** The character position for which to determine the completion proposals. */
        column: number;
        /** An optional line for which to determine the completion proposals. If missing the first line of the text is assumed. */
        line?: number;
    }
    /** Response to 'completions' request. */
    interface CompletionsResponse extends Response {
        body: {
            /** The possible completions for . */
            targets: CompletionItem[];
        };
    }
```
(from `vscode-R-debugger\node_modules\vscode-debugprotocol\lib\debugProtocol.d.ts`)

Do you think this would be possible/easy to implement using existing code?

**Comment by renkun-ken** [comment]
I guess this completion provider works in the debug console? It so, it should be different from languageserver which relies on static analysis to provide completion, i.e. there's no live session where the user code could be executed. In debugger case, there's a live R session and the environment chain is known at break point. We just need to extract all symbols in scope that start with existing user input along the environment chain.

**Comment by ManuelHentschel** [comment]
Ah ok that doesn't sound too complicated. Guess I'll look into it soon :)

**Comment by ManuelHentschel** [comment]
https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/23

Turns out the snippets provided by https://github.com/Ikuyadeu/vscode-R are already used automatically, but not the completions from https://github.com/REditorSupport/vscode-r-lsp.

**Comment by ManuelHentschel** [comment]
https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/25

This pr includes completion responses for items from the workspace (function scopes and globalenv()), but not the names of functions etc. from packages.

Getting these from all the package environments would probably be possible but super inefficient, so we should maybe find a way to get them from the languageserver, but I haven't looked into that yet.

**Comment by renkun-ken** [comment]
I guess getting the package functions from languageserver will be quite inefficient too since you have to communicate with languageserver throught LSP which is async and based on workspace and editor.

**Comment by renkun-ken** [comment]
I tried getting all symbols with specific starting character, and it is very fast. I could do a PR for this.

**Comment by renkun-ken** [comment]
languageserver provide rich information for user token in many forms such as function name `fun`, namespace and exported function `pkg::fun`, namespace and function `pkg:::fun`, package name `pkg`, exported objects like `.Machine`, language constants like `NA`, `NULL`, `FALSE`, lazy data like `mtcars`, etc.

Do we want to provide such rich completions?

**Comment by ManuelHentschel** [comment]
https://github.com/ManuelHentschel/vscDebugger/pull/23
https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/27

These PRs add completion for `pkg::fun` and `pkg:::fun` type expressions.

The reserved words/constants should be easy ro add from e.g. https://stat.ethz.ch/R-manual/R-devel/library/base/html/Reserved.html.

Regarding lazy data I wouldn't know where to find a list of these, but if we find one thez should be easy to add, too.

**Comment by renkun-ken** [comment]
https://github.com/ManuelHentschel/vscDebugger/pull/24

Adds completion of installed packages, language constants, and lazydata.

**Comment by renkun-ken** [comment]
BTW, do we want to take advantage of `CompletionItemType` to make different type of objects have different icons?

```typescript
type CompletionItemType = 'method' | 'function' | 'constructor' | 'field' | 'variable' | 'class' | 'interface' | 'module' | 'property' | 'unit' | 'value' | 'enum' | 'keyword' | 'snippet' | 'text' | 'color' | 'file' | 'reference' | 'customcolor';
```

In languageserver, we use `CompletionItemKind` which is a little different from this.

**Comment by renkun-ken** [comment]
Now the completion in debug console is quite complete.
