### ISSUE TITLE
Error in URL for downloading vscDebugger

### ISSUE THREAD

**Issue by aldopaolo** [ManuelHentschel/VSCode-R-Debugger#173]
**Describe the bug**
Command r.debugger.updateRPackage use url
  "https://github.com/ManuelHentschel/VSCode-R-Debugger/releases/download/v0.5.3/vscDebugger_0.5.3.zip"
but correct url is
  "https://github.com/ManuelHentschel/VSCode-R-Debugger/releases/download/v0.5.3/vscDebugger_0.5.**2**.zip"

**Expected behavior**
Install vscDebugger

**Actual behavior**
Error in installation

**Desktop (please complete the following information):**
 - OS: Win 11
 - R Version: 4.3.0
 - vscDebugger NA
 - vscode-r-debugger Version: 0.5.3

**Requested solution**
Correct command or correct source name

**Comment by ManuelHentschel** [comment]
Thanks for the accurate report, should be fixed by https://github.com/ManuelHentschel/VSCode-R-Debugger/commit/c0113b301499471aa4de39d2b75a2ce1805e2820.
