### ISSUE TITLE
Apple M1 Chip Compatible

### ISSUE THREAD

**Issue by lucas-vivier** [ManuelHentschel/VSCode-R-Debugger#177]
**NOTE:** Before submitting an issue, please make sure to install the latest version of both the vscode extension and the R package. This can usually be achieved by running the command `r.debugger.updateRPackage` in vscode's command palette (`F1`).

**Describe the bug**
When debugging (F5) the code a pop-up message appears: "Please install the R package "vscDebugger"!".
Yet, vscDebugger seems to be in my R distribution (I can see it from the R extension, Help pages).

In the Debug console, there is the following Error message:
"Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/vscDebugger/libs/vscDebugger.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/vscDebugger/libs/vscDebugger.so, 0x0006): tried: '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/vscDebugger/libs/vscDebugger.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/vscDebugger.so' (no such file), '/usr/lib/vscDebugger.so' (no such file)"

It seems to be related to Apple M1 Chip.
Is the R Debugger extension compatible with Apple M1 Chip?

**Your Launch config**
If applicable, the launch config that causes the bug. E.g.:
``` json
        {
            "type": "R-Debugger",
            "name": "Launch R-Workspace",
            "request": "launch",
            "debugMode": "workspace",
            "workingDirectory": "${workspaceFolder}"
        },
        {
            "type": "R-Debugger",
            "name": "Debug R-File",
            "request": "launch",
            "debugMode": "file",
            "workingDirectory": "${workspaceFolder}",
            "file": "${file}"
        },
        {
            "type": "R-Debugger",
            "name": "Debug R-Function",
            "request": "launch",
            "debugMode": "function",
            "workingDirectory": "${workspaceFolder}",
            "file": "${file}",
            "mainFunction": "main",
            "allowGlobalDebugging": false
        },
        {
            "type": "R-Debugger",
            "name": "Debug R-Package",
            "request": "launch",
            "debugMode": "workspace",
            "workingDirectory": "${workspaceFolder}",
            "includePackageScopes": true,
            "loadPackages": [
                "."
            ]
        },
        {
            "type": "R-Debugger",
            "request": "attach",
            "name": "Attach to R process",
            "splitOverwrittenOutput": true
        }
```

**Desktop (please complete the following information):**
 - OS: macOS Monterey (Chip Apple M1 Pro)
 - R Version: R version 4.3.0 (2023-04-21)
 - vscDebugger Version: version 0.5.2
 - vscode-r-debugger Version: v0.5.4

**Additional context**

**Comment by eitsupi** [comment]
I suppose you could try installing from source with something like `remotes::install_github("ManuelHentschel/vscDebugger")`.

**Comment by BPDanek** [comment]
This saved me a lot of time. Just execute the above in an R console
