### ISSUE TITLE
Use GitHub Actions to build and provide vsix

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/VSCode-R-Debugger#2]
Currently, the vsix file is commited to repo, which might not be optimal in the long run as the repo would grow too fast in size.

I recommend that we use GitHub Actions to build and provide vsix so that on each push on any branch, the package could be built and the vsix file could be uploaded to be an artifact for others to test, just like we we do in e.g. https://github.com/Ikuyadeu/vscode-R/actions/runs/114335206.

If you like this, I could create a PR to enable the GitHub actions and do some necessary setup for it to work.

**Comment by ManuelHentschel** [comment]
That would definitely be nice to have.
Thanks a lot for your contributions!
