### ISSUE TITLE
Calls to .vsc.xxx() printed to debug console

### ISSUE THREAD

**Issue by ManuelHentschel** [ManuelHentschel/VSCode-R-Debugger#28]
@renkun-ken 
I've noticed in the screenshots in https://github.com/ManuelHentschel/vscDebugger/pull/28#issue-427009742 that you see the 'echo' of function calls made by the debugger in the console output.

This problem does not exist on windows, since cmd.exe apparently does not mirror the input from `stdin` to `stdout`. I previously tried fixing the issue by filtering out all output that starts with `vscDebugger::.vsc.`, but this doesn't seem to work for long commands.

My next idea would be to temporarily store all function calls made by the debugger and match output lines against the ending of these calls or to append a unique comment (e.g. `# <v\s\c\command>`) to each command to identify these lines. Do you think this would work or do you know if there is an easier way to achieve this (some launch option for R etc.)?

**Comment by ManuelHentschel** [comment]
@renkun-ken Did these changes work for you or do you still see an 'echo' on macOS?

**Comment by renkun-ken** [comment]
It works nicely, no `echo` on macOS now.
