### ISSUE TITLE
Cannot get debugger into working

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/VSCode-R-Debugger#3]
I'm on latest develop branch of both VSCode-R-Debugger and vscodeRPackage. I build vscodeRPackage from source and run VSCode-R-Debugger. But I cannot get the debugging into working on both Ubuntu and macOS.

On macOS:

The breakpoints are not triggered:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/4662568/82961686-aa848380-9ff0-11ea-8809-b756bafdedf1.png">

The default `"rdebugger.terminal.mac": "Terminal.app"` does not work, so I change it to `/bin/bash` the same as in Linux.

The `launch.json` is default:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "R-Debugger",
      "request": "launch",
      "name": "R Debugger",
      "program": "${file}",
      "debugFunction": false,
      "allowGlobalDebugging": false
    }
  ]
}
```

On Ubuntu, it is the same.

**Comment by ManuelHentschel** [comment]
With the last commits, I added support for debugging of arbitrary R files (without the main() function). The 'new' debugging process should be:
 - press F5 to start a global workspace
 - press F5 to run the active file. The file is passed to `.vsc.debugSource`, which is similar to `source()` but sets breakpoints.
For this to work, `allowGlobalDebugging` needs to be set to `true`.
Also you need to explicitely call `main()` now (or just put everything in the top level file).

The 'old' debug mode is still available by setting `"debugFunction":true` and `"mainFunction":"main"`, but `allowGlobalDebugging` is not working properly atm (only works with `true`).

**Comment by renkun-ken** [comment]
Thanks! Just notice the latest changes.

Press F5 again is like magic, never knew we can do that in VSCode. Now it works as expected!

I'll take a closer look at the R code and hopefully I could make it into a standard package structure.
