### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by pydupont** [ManuelHentschel/VSCode-R-Debugger#48]
Hi, 

Thank you for this awesome work. I had been looking for a R debugger in vscode for a while!

I noticed that there are a lot of message in the debug console, would it be possible to hide them using an option in vscode?

It would also be great if you add the `.vsix` file on github, it would make the update much quicker :) If you don't want to put the vsix file on github, maybe you should add the instructions to build it in the readme.

Cheers!

**Comment by renkun-ken** [comment]
You could find the latest built .vsix in <https://github.com/ManuelHentschel/VSCode-R-Debugger/actions>, e.g. https://github.com/ManuelHentschel/VSCode-R-Debugger/actions/runs/144081665.

**Comment by pydupont** [comment]
Sweet! I didn't notice that. Thank!

**Comment by ManuelHentschel** [comment]
Thanks for the feedback! Would you mind posting an example of the messages you mentioned?

**Comment by pydupont** [comment]
Sure! Here is a copy of a debug session:
`Starting R session...
vscDebugger::.vsc.dispatchRequest(request=base::list(command="setExceptionBre<equest(request=base::list(command="setExceptionBrea                         kpoints",arguments=base::<command="setExceptionBreakpoints",arguments=base::l                         ist(filters=base::list("f<points",arguments=base::list(filters=base::list("fr                         omFile")),type="request",<st(filters=base::list("fromFile")),type="request",s                         eq=4)) ### <v\s\c\COMMAND<mFile")),type="request",seq=4)) ### <v\s\c\COMMAND>                         
vscDebugger::.vsc.dispatchRequest(request=base::list(command="configurationDo<equest(request=base::list(command="configurationDon                         e",type="request",seq=5))<command="configurationDone",type="request",seq=5))                          ### <v\s\c\COMMAND>
vscDebugger::.vsc.dispatchRequest(request=base::list(command="stac<c.dispatchRequest(request=base::list(command="stack`                         Trace",arguments=base::li<base::list(command="stackTrace",arguments=base::lis                         t(threadId=1,startFrame=0<race",arguments=base::list(threadId=1,startFrame=0,                         levels=20),type="request"<(threadId=1,startFrame=0,levels=20),type="request",                         seq=8)) ### <v\s\c\COMMAN<evels=20),type="request",seq=8)) ### <v\s\c\COMMAND                         >
vscDebugger::.vsc.dispatchRequest(request=base::list(command="stac<c.dispatchRequest(request=base::list(command="stack                         Trace",arguments=base::li<base::list(command="stackTrace",arguments=base::lis                         t(threadId=1,startFrame=0<race",arguments=base::list(threadId=1,startFrame=0,                         levels=20),type="request"<(threadId=1,startFrame=0,levels=20),type="request",                         seq=9)) ### <v\s\c\COMMAN<evels=20),type="request",seq=9)) ### <v\s\c\COMMAND                         >
vscDebugger::.vsc.dispatchRequest(request=base::list(command="scop<c.dispatchRequest(request=base::list(command="scope                         s",arguments=base::list(f<base::list(command="scopes",arguments=base::list(fr                         ameId=0),type="request",s<",arguments=base::list(frameId=0),type="request",se                         q=10)) ### <v\s\c\COMMAND<meId=0),type="request",seq=10)) ### <v\s\c\COMMAND>                         
vscDebugger::.vsc.dispatchRequest(request=base::list(command="vari<c.dispatchRequest(request=base::list(command="varia                         bles",arguments=base::lis<base::list(command="variables",arguments=base::list                         (variablesReference=2),ty<les",arguments=base::list(variablesReference=2),typ                         e="request",seq=11)) ### <variablesReference=2),type="request",seq=11)) ### <                         v\s\c\COMMAND>`

I am not too sure why some characters are not printed well, sorry. They appear the same here as in vscode.

Cheers

**Comment by ManuelHentschel** [comment]
Thanks!
That’s definitely not supposed to be printed... What OS and R version are you using? And did you change the R path in the debugger’s config or are you using the default?

**Comment by renkun-ken** [comment]
Would you liketo post your `sessionInfo()` in R?

**Comment by pydupont** [comment]
Hi,

Here it is:

```
R version 3.5.1 (2018-07-02)

Platform: x86_64-pc-linux-gnu (64-bit)

Running under: CentOS Linux 7 (Core)



Matrix products: default

BLAS: /usr/lib64/libblas.so.3.4.2

LAPACK: /usr/lib64/liblapack.so.3.4.2



locale:

[1] LC_CTYPE=en_NZ.UTF-8       LC_NUMERIC=C

[3] LC_TIME=en_NZ.UTF-8        LC_COLLATE=en_NZ.UTF-8

[5] LC_MONETARY=en_NZ.UTF-8    LC_MESSAGES=en_NZ.UTF-8

[7] LC_PAPER=en_NZ.UTF-8       LC_NAME=C

[9] LC_ADDRESS=C               LC_TELEPHONE=C

[11] LC_MEASUREMENT=en_NZ.UTF-8 LC_IDENTIFICATION=C



attached base packages:

[1] stats     graphics  grDevices utils     datasets  methods   base



other attached packages:

[1] curl_4.3               httr_1.4.1             jsonlite_1.6.1

[4] vscDebugger_0.0.0.9000



loaded via a namespace (and not attached):

[1] compiler_3.5.1 R6_2.4.1
```

**Comment by pydupont** [comment]
Hi,

I am on CentOs7, R 3.5.1 and I am not using the default R of my system, I changed it in the config file.

Cheers

**Comment by ManuelHentschel** [comment]
I guess, the `���...` are control characters (backspace?) added by the terminal to trim long input lines. As far as I'm aware, these do not show up with bash on ubuntu or on macOS. On these platforms we manage to filter out the echo of our inputs by looking for the comment ` ### <v\s\c\COMMAND>` added to the end of each line.

I am trying to figure out a way to reduce/eliminate the need for output filtering in general, but this is not so easy, since some of the stuff printed to stdout is hardcoded into R itself.

As a workaround I added an option to hide all output to stdout in https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/50. Note that the debugger's custom versions of `cat` and `print` still work with `printStdout` set to `nothing`, since they do not print to stdout but instead send an output event to the debugger. However, you won't see any output generated by other functions like `message`, `writeLines`, `print.default`.

Does this work for you?

**Comment by pydupont** [comment]
Sorry for the late answer.

It works, thanks! I close the issue.
