### ISSUE TITLE
Call stack not showing function calls correctly

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/VSCode-R-Debugger#64]
I'm testing against the latest development version and the call stack does not seem to work correctly:

<img width="975" alt="image" src="https://user-images.githubusercontent.com/4662568/90658470-33206200-e276-11ea-97fc-5e873e033897.png">

**Comment by ManuelHentschel** [comment]
Thanks for catching that!

**Comment by renkun-ken** [comment]
Thanks for the quick fix!
