### ISSUE TITLE
Debug R-Function failed after file changed its name

### ISSUE THREAD

**Issue by Maswor** [ManuelHentschel/VSCode-R-Debugger#69]
**Steps to reproduce:**

- Create a `my_R_function.R` and run debug function with it
- Change the file to `R_function.R`

**Expected Behavior**
- Debugger run

**Actual Behavior**
- Warning message: In normalizePath(lget(args$source, "path", "")) :
  path[1]="/USER_PATH/my_R_functions.R": No such file or directory

**Comment by ManuelHentschel** [comment]
Did you specify a file name in your `launch.json`?
The default should be `"file": "${file}"` which will source the active file and then look for your main function.
If you specified `my_R_function.R` here, this needs to be changed to `R_function.R` as well.

**Comment by renkun-ken** [comment]
I notice this too which could be quite annoying.

This could happen without using the path in `launch.json`. We only need to set some breakpoints in the file and rename the file (maybe outside vscode?). The remembered breakpoints are pointed to the old file name which is invalid.

**Comment by ManuelHentschel** [comment]
Did the changes in the PR work, or are you still having problems?

**Comment by Maswor** [comment]
I'm using version on Market Place, so it could be behind the master branch. I made a simple fix by using `Debug file` and manually run `main()` function!
