### ISSUE TITLE
debugger says "Please install the R package vscDebugger" even though it is already installed.

### ISSUE THREAD

**Issue by xinstein** [ManuelHentschel/VSCode-R-Debugger#74]
my launch setting:
```
        {
            "name": "R: Current File",
            "debugMode": "file",
            "type": "R-Debugger",
            "request": "launch",
            "workingDirectory": "${fileDirname}",
        }
```

my rdebugger setting:
"rdebugger.rterm.windows": "\"Z:\\Program Files\\R\\R-3.5.3\\bin\\R.exe\""

**Comment by xinstein** [comment]
Please guide me through providing additional information

**Comment by ManuelHentschel** [comment]
Could you please verify that you have version 0.2.0 of both the VS Code extension and the R package installed:

In a regular R terminal session:
``` r
> packageVersion('vscDebugger')
[1] '0.2.0'
```

In the Extensions view:
![VS Code version](https://user-images.githubusercontent.com/53863351/92696707-8e5fe480-f34a-11ea-972f-d810e340f9b2.PNG)

**Comment by xinstein** [comment]
![image](https://user-images.githubusercontent.com/10842079/92703469-c71caf80-f384-11ea-9d04-0146a19bd8a0.png)

![image](https://user-images.githubusercontent.com/10842079/92703519-d1d74480-f384-11ea-8183-481538ed786c.png)

They are indeed

**Comment by xinstein** [comment]
I might have forgotten to mention that my OS is windows 10.

**Comment by ManuelHentschel** [comment]
Thanks for the info!

It seems like your R version (3.5.3) causes problems. I am personally using 4.0.2, and the package seems to work fine with 3.6.1, but not with a fresh installation of R 3.5.3.

If you have the possibility to do so, I recommend upgrading R to the latest version (or at least 3.6.X) and trying again.

If you are bound to R 3.5.3 you could try installing the package from code (using `devtools::install` and [Rtools](https://cran.r-project.org/bin/windows/Rtools/history.html)).

Please let me know if either of these options work for you :)

**Comment by xinstein** [comment]
Thank you very much, both approaches work!
 I've gone with the install-from-source solution since reinstalling all my required R packages is a bit tiresome.
