### ISSUE TITLE
restart debugging for Debug R-File broken

### ISSUE THREAD

**Issue by FelixBenning** [ManuelHentschel/VSCode-R-Debugger#77]
The restart button (`Ctrl+Shift+F5`) seems broken when using `Debug R-File`. 

### System

docker image `rocker/r-ver:4.0.0`

### Workaround

Stopping debugging and restarting seems to work.

**Comment by ManuelHentschel** [comment]
Thanks for catching that!

The Restart button is currently being "abused" to exit a function without terminating the R session itself (the "Stop" button always terminates both the function and the R session itself).

This was meant as a temporary workaround, which I forgot about. I'll look into that, should be easy to fix :)
