### ISSUE TITLE
Different colors of print and message

### ISSUE THREAD

**Issue by bersbersbers** [ManuelHentschel/VSCode-R-Debugger#98]
**Describe the bug**
I am still trying to find out what the different colors means in the VS Code Debug Console, but I already noticed that `print` and `message` produce different colors. Is this intended? I do not see any semantic difference between the two.

**To Reproduce**
![image](https://user-images.githubusercontent.com/12128514/96562897-956f0080-12c1-11eb-93b2-db31a0fa4af4.png)

**Your R code**
```R
print(1)
message(1)
```

**Your Launch config**
If applicable, the launch config that causes the bug. E.g.:
``` json
        {
            "type": "R-Debugger",
            "request": "launch",
            "name": "Debug R-File",
            "debugMode": "file",
            "workingDirectory": "${workspaceFolder}",
            "file": "${file}",
            "allowGlobalDebugging": true
        }
```

**Expected behavior**
Identical colors (I believe)

**Comment by ManuelHentschel** [comment]
The specific colours are mostly controlled by VS Code, the extension has only indirect influence on the colours by using different "output channels":
* Text that is sent as normal output to the debug console is blue. This is mostly text that is printed to R's stdout by e.g.  `print()` and `cat()`.
* Text that is sent as error output (i.e. "stderr") is shown red. This includes `message()` from you example, as well as `error()`, `cat(..., file=stderr())` etc.
* Text that is sent in a "structured" way is formatted by VS Code. This includes the result of evaluate-requests entered in the debug console and output produced by `.vsc.str()`. The colours are pretty much the same as in the variables window. Usually, numerical values will be shown green, strings orange, names of child variables purple, and everything else grey.

*Note: The specific colours probably vary depending on the selected colour theme, the ones I described above are from `Dark+`*

**Comment by bersbersbers** [comment]
Oh my:
> The default handler sends the message to the `stderr()` connection.

https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/message

Related: https://stackoverflow.com/questions/25306819/send-r-diagnostic-messages-to-stdout-instead-stderr

I did not know that. Thank you and sorry for the noise.
